### ISSUE TITLE
Better GIFs on RAEDME

### ISSUE THREAD

**Issue by baristaGeek** [watermelontools/watermelon-extension#346]
The GIFs on our README are outdated and pixelated. 

We should have high quality GIFs that show the product with the most recent changes

**Comment by EstebanDalelR** [comment]
Seems impactful. I recommend my setup on mac:
- Record with the Screenshot app
- Edit whatever needed in iMovie
- Use [Adobe Express ](https://express.adobe.com/tools/convert-to-gif)to convert to video (use highest quality and 32FPS)

**Comment by olegkron** [comment]
#348 
Let me know if those work

**Comment by EstebanDalelR** [comment]
@baristaGeek ?
